name: Cypress Tests (Commit Message Triggers)
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    continue-on-error: true
    env:
      NODE_VERSION: 22
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Init submodules
        run: git submodule update --init --recursive
      - name: Check for brackets in commit messages
        id: check-commits
        run: |
          COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
          COMMIT_MESSAGE=$(git log -1 --pretty=%B $COMMIT_SHA)
          echo "Latest commit message: $COMMIT_MESSAGE"
          if echo "$COMMIT_MESSAGE" | grep -q "\[.*\]"; then
            echo "has_brackets=true" >> $GITHUB_OUTPUT
            echo "has_valid_tags=true" >> $GITHUB_OUTPUT
            echo "commit_messages<<EOF" >> $GITHUB_OUTPUT
            echo "$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "has_brackets=false" >> $GITHUB_OUTPUT
            echo "No commit messages with square brackets found"
            echo "has_valid_tags=false" >> $GITHUB_OUTPUT
            exit 0
          fi
      - name: Determine combined test specs
        if: steps.check-commits.outputs.has_brackets == 'true'
        id: test_specs
        run: |
          SPECS=""
          MSG_LOWER=$(echo "${{ steps.check-commits.outputs.commit_messages }}" | tr '[:upper:]' '[:lower:]')
          echo "Commit message (lowercase): $MSG_LOWER"
          TAGS=$(echo "$MSG_LOWER" | grep -oE '\[[^]]+\]' | sed 's/[][]//g' | tr ',' '\n' | sed 's/^ *//; s/ *$//')
          echo "Extracted tags:"
          echo "$TAGS"
          for tag in $TAGS; do
            case "$tag" in
              spins)
                echo "Matched tag: spins"
                SPECS+="cypress/e2e/MotoGPRoulette/Spins/Spins.cy.js,"
                ;;
              features)
                echo "Matched tag: features"
                SPECS+="cypress/e2e/MotoGPRoulette/Features/Features.cy.js,"
                ;;
              bonus)
                echo "Matched tag: bonus"
                SPECS+="cypress/e2e/MotoGPRoulette/Spins/bonus_and_autospin_stop_on_bonus_feature.cy.js,"
                ;;
              bets)
                echo "Matched tag: bets"
                SPECS+="cypress/e2e/MotoGPRoulette/Stakes/inside_bets.cy.js,"
                SPECS+="cypress/e2e/MotoGPRoulette/Stakes/outside_bets.cy.js,"
                SPECS+="cypress/e2e/MotoGPRoulette/Stakes/race_sectors_bets.cy.js,"
                ;;
              *)
                echo "Unknown tag: $tag (ignored)"
                ;;
            esac
          done
          SPECS=${SPECS%,}
          echo "Final SPECS: $SPECS"
          if [ -z "$SPECS" ]; then
            echo "❌ No matching tags found in commit message. Skipping tests."
            echo "specs=" >> $GITHUB_OUTPUT
            exit 78
          fi
          echo "✅ Specs selected: $SPECS"
          echo "specs=$SPECS" >> $GITHUB_OUTPUT
      - name: Setup Node.js
        if: steps.check-commits.outputs.has_brackets == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules and .npm
        if: steps.check-commits.outputs.has_brackets == 'true'
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            ~/.npm
            external/node_modules
          key: ${{ runner.os }}-node-modules-external
      - name: Install dependencies (if needed)
        if: steps.npm-cache.outputs.cache-hit != 'true'
        working-directory: external
        run: npm install
      - name: Install wait-on
        if: steps.check-commits.outputs.has_brackets == 'true'
        run: npm install --no-save wait-on
      - name: Cache Cypress binary
        if: steps.check-commits.outputs.has_brackets == 'true'
        uses: actions/cache@v4
        id: cypress-cache
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-external
      - name: Create reports directory
        if: steps.check-commits.outputs.has_brackets == 'true'
        run: mkdir -p external/reports/chrome
      - name: Start local server
        if: steps.check-commits.outputs.has_brackets == 'true'
        run: |
          npm run build:test
          npx serve -s dist -l 8000 &
        continue-on-error: false
      - name: Wait for local server
        if: steps.check-commits.outputs.has_brackets == 'true'
        run: npx wait-on http://localhost:8000
      - name: Check if server is up
        if: steps.check-commits.outputs.has_brackets == 'true'
        run: |
          curl -I http://localhost:8000 || (echo "Server not running!" && exit 1)
      - name: Show test specs
        if: steps.check-commits.outputs.has_brackets == 'true'
        working-directory: external
        run: |
          echo "Test specs: ${{ steps.test_specs.outputs.specs }}"
          IFS=',' read -ra SPEC_ARRAY <<< "${{ steps.test_specs.outputs.specs }}"
          for spec in "${SPEC_ARRAY[@]}"; do
            ls -l "$spec" || echo "Test file not found: $spec"
          done
      - name: Run Cypress tests in Chrome
        if: steps.check-commits.outputs.has_brackets == 'true'
        working-directory: external
        env:
          TERM: xterm
        run: |
          IFS=',' read -ra SPEC_ARRAY <<< "${{ steps.test_specs.outputs.specs }}"
          for spec in "${SPEC_ARRAY[@]}"; do
            echo "Running test: $spec"
            npx cypress run \
              --browser chrome \
              --spec "$spec" \
              --reporter mochawesome \
              --reporter-options "reportDir=reports/chrome,overwrite=false,html=false,json=true" \
              --config video=true,chromeWebSecurity=false
          done
      - name: List generated reports
        if: steps.check-commits.outputs.has_brackets == 'true'
        working-directory: external
        run: |
          ls -l reports/chrome || echo "No reports directory found"
          ls -l reports/chrome/*.json || echo "No JSON reports found"
      - name: Merge Mochawesome reports
        if: steps.check-commits.outputs.has_brackets == 'true'
        working-directory: external
        run: |
          npx mochawesome-merge reports/chrome/*.json > reports/chrome/merged-report.json
      - name: Generate HTML reports
        if: steps.check-commits.outputs.has_brackets == 'true'
        working-directory: external
        run: |
          npx marge reports/chrome/merged-report.json \
            --reportDir reports/chrome \
            --reportFilename chrome-report.html \
            --inline
      - name: Upload HTML Reports
        if: steps.check-commits.outputs.has_brackets == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: chrome-test-report
          path: external/reports/chrome/chrome-report.html
      - name: Upload Test Videos
        if: steps.check-commits.outputs.has_brackets == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: chrome-test-videos
          path: external/cypress/videos
