name: Cypress Tests

on: 
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browsers: [chrome, firefox, edge]
    
    env:
      NODE_VERSION: 22
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      # More precise caching for npm
      - name: Cache npm dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      # Only install if cache missed
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm ci
          npm install mochawesome mochawesome-merge mochawesome-report-generator
      
      # Cache Cypress binary
      - name: Cache Cypress
        uses: actions/cache@v4
        id: cypress-cache
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
      
      - name: Determine test spec
        id: test-spec
        run: |
          # Convert commit message to lowercase for case-insensitive matching
          COMMIT_MSG=$(echo "${{ github.event.head_commit.message }}" | tr '[:upper:]' '[:lower:]')
          
          if [[ $COMMIT_MSG == *"localization"* ]]; then
            echo "SPEC=gg.translation.cy.js" >> $GITHUB_OUTPUT
          else
            echo "SPEC=cypress/e2e/**/!(*translation*).cy.js" >> $GITHUB_OUTPUT
          fi
          
      - name: Create reports directory
        run: mkdir -p cypress/reports/${{ matrix.browsers }}
          
      - name: Cypress run
        run: |
          npx cypress run \
            --browser ${{ matrix.browsers }} \
            --spec "cypress/e2e/MotoGPRoulette/Burger_Menu/${{ steps.test-spec.outputs.SPEC }}" \
            --reporter mochawesome \
            --reporter-options "reportDir=cypress/reports/${{ matrix.browsers }},overwrite=false,html=false,json=true"
          
      - name: Merge Mochawesome Reports
        if: always()
        run: |
          npx mochawesome-merge cypress/reports/${{ matrix.browsers }}/*.json > cypress/reports/${{ matrix.browsers }}/merged-report.json
          
      - name: Generate HTML Reports
        if: always()
        run: |
          npx marge cypress/reports/${{ matrix.browsers }}/merged-report.json \
            --reportDir cypress/reports/${{ matrix.browsers }} \
            --reportFilename ${{ matrix.browsers }}-report.html \
            --inline
          
      - name: Upload HTML Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.browsers }}-test-report
          path: cypress/reports/${{ matrix.browsers }}/${{ matrix.browsers }}-report.html