name: Cypress Tests (Chrome Only)

on: 
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    env:
      NODE_VERSION: 22
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get commit message
        id: commit_message
        run: echo "message=$(git log -1 --pretty=%B | head -n 1)" >> $GITHUB_OUTPUT

      - name: Determine test folder
        id: test_folder
        run: |
          if [[ "${{ steps.commit_message.outputs.message }}" == *"Burger"* ]]; then
            echo "folder=cypress/e2e/MotoGPRoulette/Burger_Menu" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.commit_message.outputs.message }}" == *"Features"* ]]; then
            echo "folder=cypress/e2e/MotoGPRoulette/Features" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.commit_message.outputs.message }}" == *"Spins"* ]]; then
            echo "folder=cypress/e2e/MotoGPRoulette/Spins" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.commit_message.outputs.message }}" == *"Stakes"* ]]; then
            echo "folder=cypress/e2e/MotoGPRoulette/Stakes" >> $GITHUB_OUTPUT
          else
            echo "folder=cypress/e2e" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache node_modules and .npm
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies (if needed)
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      # Removed global installation - using local packages instead
      - name: Verify mochawesome packages
        run: npm list mochawesome mochawesome-merge mochawesome-report-generator

      - name: Cache Cypress binary
        uses: actions/cache@v4
        id: cypress-cache
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: Create reports directory
        run: mkdir -p cypress/reports/chrome

      - name: Run Cypress tests in Chrome
        env:
          TERM: dumb  # Fixes the "tput" error
        run: |
          npx cypress run \
            --browser chrome \
            --spec "${{ steps.test_folder.outputs.folder }}/**/*.cy.js" \
            --reporter mochawesome \
            --reporter-options "reportDir=cypress/reports/chrome,overwrite=false,html=false,json=true" \
            --config video=true

      # Updated report generation steps using npx
      - name: Merge Mochawesome reports
        if: always()
        run: |
          npx mochawesome-merge@4.2.2 cypress/reports/chrome/*.json > cypress/reports/chrome/merged-report.json

      - name: Generate HTML reports
        if: always()
        run: |
          npx marge cypress/reports/chrome/merged-report.json \
            --reportDir cypress/reports/chrome \
            --reportFilename chrome-report.html \
            --inline

      - name: Verify reports exist
        if: always()
        run: |
          ls -la cypress/reports/chrome/
          test -f cypress/reports/chrome/chrome-report.html || echo "HTML report missing"

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: chrome-test-report
          path: cypress/reports/chrome/chrome-report.html

      - name: Upload Test Videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: chrome-test-videos
          path: cypress/videos