name: Cypress Tests

on: 
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browsers: [chrome, firefox, edge]
    
    env:
      NODE_VERSION: 22
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get commit message
        id: commit_message
        run: echo "message=$(git log -1 --pretty=%B | head -n 1)" >> $GITHUB_OUTPUT
      
      - name: Determine test folder
        id: test_folder
        run: |
          if [[ "${{ steps.commit_message.outputs.message }}" == *"Burger"* ]]; then
            echo "folder=cypress/e2e/MotoGPRoulette/Burger_Menu" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.commit_message.outputs.message }}" == *"Features"* ]]; then
            echo "folder=cypress/e2e/MotoGPRoulette/Features" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.commit_message.outputs.message }}" == *"Spins"* ]]; then
            echo "folder=cypress/e2e/MotoGPRoulette/Spins" >> $GITHUB_OUTPUT
          elif [[ "${{ steps.commit_message.outputs.message }}" == *"Stakes"* ]]; then
            echo "folder=cypress/e2e/MotoGPRoulette/Stakes" >> $GITHUB_OUTPUT
          else
            echo "folder=cypress/e2e" >> $GITHUB_OUTPUT
          fi
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'  # This handles npm caching automatically
      
      # Remove the manual npm cache step since setup-node handles it
      - name: Install dependencies
        run: |
          npm ci --prefer-offline
          ls -la node_modules/mochawesome || npm install mochawesome mochawesome-merge mochawesome-report-generator
      
      - name: Verify Mochawesome Cache
        run: |
          ls -la node_modules/mochawesome
          npm ls mochawesome mochawesome-merge mochawesome-report-generator

      - name: Cache Cypress
        uses: actions/cache@v4
        id: cypress-cache
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          
      - name: Create reports directory
        run: mkdir -p cypress/reports/${{ matrix.browsers }}
          
      - name: Cypress run
        run: |
          # Add NODE_PATH to ensure module resolution
          NODE_PATH=./node_modules npx cypress run \
            --browser ${{ matrix.browsers }} \
            --spec "${{ steps.test_folder.outputs.folder }}/**/*.cy.js"
          
      - name: Merge Mochawesome Reports
        if: always()
        run: |
          npx mochawesome-merge cypress/reports/${{ matrix.browsers }}/*.json > cypress/reports/${{ matrix.browsers }}/merged-report.json
          
      - name: Generate HTML Reports
        if: always()
        run: |
          npx marge cypress/reports/${{ matrix.browsers }}/merged-report.json \
            --reportDir cypress/reports/${{ matrix.browsers }} \
            --reportFilename ${{ matrix.browsers }}-report.html \
            --inline
          
      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.browsers }}-test-report
          path: cypress/reports/${{ matrix.browsers }}/${{ matrix.browsers }}-report.html